#!/usr/bin/env python3
"""
Initialize Euro Hotel rooms with updated configuration
Contact: rudraramreservations@eurohotel.in
Phone: +91 77299 00091

Run this script from the backend directory:
python init_euro_hotel_rooms.py
"""

print("Euro Hotel Room Configuration Update")
print("=" * 50)
print()
print("New Room Structure:")
print("- EH Deluxe Highway View: 2 rooms @ ₹6,500 + GST")
print("- EH Premium: 15 rooms @ ₹5,000 + GST") 
print("- EH Superior: 19 rooms @ ₹4,000 + GST")
print("Total: 36 rooms")
print()
print("Updated Policies:")
print("- GST: 5% for rooms under ₹7,500")
print("- Cancellation: 48 hours before check-in")
print("- Extra bed charges: ₹1,500")
print("- Room stay ID required")
print("- No outside guests allowed")
print("- No smoking in rooms (separate smoking zone)")
print()
print("Contact Information:")
print("- Email: rudraramreservations@eurohotel.in")
print("- Phone: +91 77299 00091")
print("- Address: Euro Hotel, Opp post office Mumbai highway")
print("  Rudraram village Patancheru Mandal Sangareddy Dist Telangana 502329")
print()
print("Restaurant & Services:")
print("- nH-65 Fine Dining Restaurant (First floor, 12pm-12am)")
print("- nH-65 Casual Dining Restaurant (7am-12am)")
print("- Barista Cafe (24x7)")
print("- Room F&B Service (7am-12pm)")
print("- 220 cover restaurant with multicuisine")
print("- Private dining areas (18 & 15 pax)")
print("- Mocktail bar, live kitchen, ice cream parlour")
print()
print("Hotel Services:")
print("- 24x7 cab facility & airport pickup/drop")
print("- Laundry facility")
print("- WiFi throughout")
print("- Butler service")
print("- Tour planning & ticket booking")
print("- Corporate & group tour management")
print("- Kitty parties & catering services")
print()
print("Payment Gateway: Razorpay")
print("Future: Indoor banquet hall (2nd phase)")
print()
print("Files Updated:")
print("✓ Room models with new types")
print("✓ GST calculation (5% under ₹7,500)")
print("✓ Cancellation policy (48 hours)")
print("✓ Contact information")
print("✓ Hotel configuration")
print("✓ Frontend footer")
print()
print("Next Steps:")
print("1. Run the backend server to apply database changes")
print("2. Update frontend environment variables if needed")
print("3. Test the booking system with new pricing")
print("4. Update any email templates with new contact info")
print()
print("Configuration complete! 🎉")